haproxy:
  image: haproxy-alpine:3.0
  container_name: rinha-haproxy
  volumes:
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  depends_on:
    - api01
    - api02
  ports:
    - "9999:9999"
  networks:
    - backend
    - payment-processor
  deploy:
    resources:
      limits:
        cpus: "0.1"
        memory: "15MB"
api01:
  image: ghcr.io/gabriell915/api-rinha-backend-quarkus-2025:latest
  environment:
    PAYMENT_PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
    PAYMENT_PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
    DB_HOST: "jdbc:postgresql://postgres:5432/rinha-backend"
    DB_USERNAME: "rinha"
    DB_PASSWORD: "rinha123"
  networks:
    - backend
    - payment-processor
  depends_on:
    - postgres
  deploy:
    resources:
      limits:
        cpus: "0.6"
        memory: "65MB"
  api02:
    image: ghcr.io/gabriell915/api-rinha-backend-quarkus-2025:latest
    environment:
      PAYMENT_PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
      PAYMENT_PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
      DB_HOST: "jdbc:postgresql://postgres:5432/rinha-backend"
      DB_USERNAME: "rinha"
      DB_PASSWORD: "rinha123"
    networks:
      - backend
      - payment-processor
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "65MB"
  postgres:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_USER: "rinha"
      POSTGRES_PASSWORD: "rinha123"
      POSTGRES_DB: "rinha-backend"
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "70MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true